language: node_js
node_js:
  - "0.12"

services:
  - couchdb

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - node reset-db.js --reinstall # setup cashew couchdb
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give stuff time to start

script:
  - node_modules/.bin/jshint app/ couchdb/ cashew-server.js reset-db.js --config .jshintrc --exclude app/bower_components
  - node_modules/.bin/mocha ./test/unit/cashewServerTest.js
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - node_modules/.bin/protractor test/e2e/protractor.conf.js --browser=firefox
